############################################################
# Dockerfile to build an Ubuntu instance with ping
# to be used with NS3.
# Based on Ubuntu
############################################################

FROM ubuntu
MAINTAINER <Chepe Alvarez chepeftw@gmail.com>

RUN apt-get update && apt-get install -y \
    inetutils-ping \
    net-tools \
    golang \
    git
